### ISSUE TITLE
sobol and egs_sobol libraries do not get built on Windows

### ISSUE THREAD

**Issue by mchamberland** [clrp-code/EGSnrc_CLRP#4]
I ended up with a Windows laptop at work, so I'm trying to get egs_brachy to run properly on Windows.

I'm stuck at the part where building egs_autoenvelope does not create .dll and .lib files for sobol and egs_sobol.

@randlet any ideas?

**Comment by randlet** [comment]
I have not tried to compile anything on Windows so not sure.  Wild guess: the makefile has a check to [see if sobol.cpp exists](https://github.com/clrp-code/EGSnrc_with_egs_brachy/blob/egs_brachy/HEN_HOUSE/egs%2B%2B/geometry/egs_autoenvelope/Makefile#L14) . Maybe that doesn't work on Windows?  Maybe try removing that check and see if it builds?

**Comment by mchamberland** [comment]
That was my first thought, too. I tried removing the check, but no luck.

**Comment by mchamberland** [comment]
I'll try comparing the log when building on my Mac vs on Windows to find which commands are missing.

**Comment by randlet** [comment]
So what does `make` show when you run it in the egs_autoenvelope directory?  You could try compiling it manually like:

```

g++ -I/home/randlet/EGSnrc/HEN_HOUSE/egs++/../lib/linux -I/home/randlet/EGSnrc/HEN_HOUSE/egs++/ -fPIC -DBUILD_AENVELOPE_DLL -DBUILD_SOBOL_DLL -DBUILD_AE_SOBOL -DHAS_SOBOL -DBUILD_GZSTREAM -DHAS_GZSTREAM -O3 -ffast-math -Wall -g -o/home/randlet/EGSnrc/HEN_HOUSE/egs++/dso/linux/sobol.o sobol.cpp

```

(with correct paths obviously!)

**Comment by mchamberland** [comment]
Building with mingw32-make on Windows yields:
```
g++ -IC:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\..\lib\win3264 -IC:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\ -DWIN32 -fPIC -DBUILD_AENVELOPE_DLL -DBUILD_SOBOL_DLL -DBUILD_AE_SOBOL -DHAS_SOBOL -DBUILD_GZSTREAM -DHAS_GZSTREAM -O2 -mtune=native -c -o C:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264\egs_autoenvelope.o egs_autoenvelope.cpp
g++ -IC:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\..\lib\win3264 -IC:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\ -DWIN32 -fPIC -DBUILD_AENVELOPE_DLL -DBUILD_SOBOL_DLL -DBUILD_AE_SOBOL -DHAS_SOBOL -DBUILD_GZSTREAM -DHAS_GZSTREAM -O2 -mtune=native -c -o C:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264\sobol.o sobol.cpp
g++ -IC:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\..\lib\win3264 -IC:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\ -DWIN32 -fPIC -DBUILD_AENVELOPE_DLL -DBUILD_SOBOL_DLL -DBUILD_AE_SOBOL -DHAS_SOBOL -DBUILD_GZSTREAM -DHAS_GZSTREAM -O2 -mtune=native -c -o C:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264\egs_sobol.o egs_sobol.cpp
g++ -IC:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\..\lib\win3264 -IC:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\ -DWIN32 -fPIC -DBUILD_AENVELOPE_DLL -DBUILD_SOBOL_DLL -DBUILD_AE_SOBOL -DHAS_SOBOL -DBUILD_GZSTREAM -DHAS_GZSTREAM -O2 -mtune=native -shared -LC:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264 C:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264\egs_autoenvelope.o C:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264\sobol.o C:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264\egs_sobol.o C:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264\gzstream.o -o C:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264\egs_autoenvelope.dll -Wl,--out-implib,C:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264\egs_autoenvelope.lib  -legs_gtransformed -legspp -lz

```

Running what you wrote yields a "file not found" error for egs_rndm.h, which must be caused by something really obvious, but I'm out of my element in Windows. >.<

**Comment by mchamberland** [comment]
Wait, I had a typo in my path. Oops.

**Comment by mchamberland** [comment]
Now it complains about an undefined reference to 'WinMain'. Some sort of progress, I guess!

**Comment by mchamberland** [comment]
We may need to pass the `-lmingw32` flag while linking. Where would I pass that flag in that command you wrote above?

**Comment by randlet** [comment]
Doubt it matters to much. You can probably stick it after the -Wall

**Comment by mchamberland** [comment]
No luck for now.

**Comment by mchamberland** [comment]
Huh. I guess libraries are also not built on the Mac. Maybe that's not the problem? Hmm... I need to look into it more tomorrow on Windows.

**Comment by mchamberland** [comment]
Okay, so on my Mac, only sobol.o and egs_sobol.o are built and I can compile `egs_brachy` just fine.

On Windows, when building egs_brachy, I get the following:

```
g++ -O2 -mtune=native -o C:\Users\m310767\dev\EGSnrc\egs_home\bin\win3264\egs_brachy.exe egs_brachy_win3264.o phantom_win3264.o eb_volcor_win3264.o latch_win3264.o spec_scoring_win3264.o pubsub_win3264.o ginfo_win3264.o recycle_win3264.o phsp_win3264.o gzstream_win3264.o egs_advanced_application_win3264.o egsnrc_win3264.o egs_interface2_win3264.o -LC:\Users\m310767\dev\EGSnrc\HEN_HOUSE\egs++\dso\win3264 -legspp -lgfortran  -legs_autoenvelope -liaea_phsp -lz
eb_volcor_win3264.o:eb_volcor.cpp:(.text+0xc9b): undefined reference to `EGS_Sobol::setState(int, long long)'
eb_volcor_win3264.o:eb_volcor.cpp:(.text+0xcf4): undefined reference to `sobol::tau_sobol(int)'
eb_volcor_win3264.o:eb_volcor.cpp:(.text+0xd08): undefined reference to `EGS_Sobol::setState(int, long long)'
eb_volcor_win3264.o:eb_volcor.cpp:(.text+0xd55): undefined reference to `sobol::tau_sobol(int)'
eb_volcor_win3264.o:eb_volcor.cpp:(.rdata$.refptr._ZTV9EGS_Sobol[.refptr._ZTV9EGS_Sobol]+0x0): undefined reference to `vtable for EGS_Sobol'
collect2.exe: error: ld returned 1 exit status
```

So, what's missing here?

**Comment by mchamberland** [comment]
I found a workaround: copy the sobol and egs_sobol files to the egs_brachy source directory and build them with egs_brachy. Problem partially solved?

**Comment by randlet** [comment]
Progress at least!  I do have a Win 10 VM, so I can take a look at some point and see if I can figure anything out.

**Comment by mchamberland** [comment]
In the meantime, [this commit](https://github.com/clrp-code/egs_brachy/commit/177390761acc6e18b9124e6efdfb81330f0ded80) on the egs_brachy repo acts as a workaround.

**Comment by mchamberland** [comment]
I don’t have access to a Windows environment to test this and Windows users are encouraged to use the Windows Subsystem for Linux nowadays.
